name: check-env

on:
  push:
    branches:
      - main
jobs:
  set-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        id: set-env
        run: |
          echo "AAA=AAAAAAA" >> $GITHUB_ENV

      - name: get env
        id: get-env
        run: |
          echo ${{env.AAA}}
