name: test-gh-actions-release

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+"
jobs:
  test-release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "release"