name: test-gh-actions-release

on:
  release:
    types: [ published ]
    releases:
      - v*
jobs:
  test-release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "release"