name: test-gh-actions-release

on:
  release:
    types: [ published ]
jobs:
  test-release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref: ${{ github.ref }}"
          echo "action_ref: ${{ github.action_ref }}"
          echo "release: ${{ github.event.release }}"
          echo "github.release: ${{ github.release }}"
