name: test-gh-actions-release

on:
  push:
    tags-ignore:
      - '**rc**'
jobs:
  test-release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "release"